#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

# Update and upgrade packages
sudo apt-get -y  update
sudo apt-get -y upgrade

# Install nginx
sudo apt-get -y install nginx

sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i '23i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
