#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Update and upgrade packages

sudo apt-get -y  update
sudo apt-get -y upgrade
# Install nginx
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '23i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_page.html

sudo sed -i '24i\error_page 404 /404_page.html; location = /404_page.html { root /usr/share/nginx/html/404_page.html; internal;}' /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
