#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Your script should only display:
# username
#user id
# Home directory path for the user

while IFS= read -r line;
do
   user_name=$(echo $line | cut -d: -f1)
   user_id=$(echo $line | cut -d: -f3)
   home_dir=$(echo $line | cut -d: -f6)

	echo "$user_name:$user_id:$home_dir"
done <  /etc/passwd
