#!/usr/bin/env bash
# gives you information about the a file.


for file in *
do
	if [ "$file" == "school" ]
	then
		echo "school file exists"
		if [ -z "$file" ]
		then
			echo "school file is empty"
		elif [ -s "$file" ]
		then
			echo "school file is not empty"
		elif [ -f "$file" ]
		then
			echo "school is a regular file"
		else
			echo ""
		fi
	else
		echo "school file does not exist"
	fi
done
