#!/bin/env bash
# Bash script that will create an RSA key pair

# Set the key name
key_name="school"

# Set the number of bits in the key
key_bits=4096

# Set the passphrase
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b "$key_bits" -P "$passphrase" -f "$key_name"
